### ISSUE TITLE
Installing Dependencies

### ISSUE THREAD

**Issue by mjtavarez** [Pizzaface/Alexa-Chromecast-Skill-2.0#17]
Hi, I am getting stuck on Step 4 installing the local dependencies.

When I enter "sudo pip install -r ./src/local/requirements.txt" I get the following error.
``` 
File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-WU06KS/miniupnpc/setup.py", line 20, in run
        subprocess.check_call([os.environ.get('MAKE', 'make')] + EXT)
      File "/usr/lib64/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'libminiupnpc.a']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-WU06KS/miniupnpc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mAluUX-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-WU06KS/miniupnpc/
```
I tried then to install setuptools via "pip install -U setuptools" but I got the following.
```
Collecting setuptools
  Using cached setuptools-36.4.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 12.2
    Uninstalling setuptools-12.2:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib64/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/bin/easy_install'
```
Any idea what might be happening?

**Comment by Pizzaface** [comment]
Make sure you're using pip3, I believe the script requires it.

**Comment by mjtavarez** [comment]
Thanks. Apparently I was still using python2.7 to compile even after installing python3.5. I had to create a sym link inside /usr/bin pointing to the path returned by whereis pip-3.5.

I was also missing the gcc package which was giving me compile errors.

Now I'm stuck at trying to run ./start.sh I keep getting
```
[ec2-user@Alexa-Chromecast-Skill-2.0-master]$ ./start.sh
-bash: ./start.sh: Permission denied
```
or

```
[ec2-user@ip-172-31-28-149 Alexa-Chromecast-Skill-2.0-master]$ sh ./start.sh
./start.sh: line 7: .: .env: file not found
```

Thanks for all of your help! I am very new to programming.
