### ISSUE TITLE
UnicodeDecodeError when running aws-setup.sh

### ISSUE THREAD

**Issue by Who-Code** [Pizzaface/Alexa-Chromecast-Skill-2.0#19]
When running aws-setup.sh following Error occurs: 

```
Creating AmazonAlexaSkill role.

Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 56, in main
    return driver.main()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 227, in main
    err.write(six.text_type(e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 39: ordinal not in range(128)

```
I configured AWS for region eu-central-1 and json as output format.
Any solutions or workarounds ?

**Comment by jinxo13** [comment]
Can you try this with the latest release?
