### ISSUE TITLE
./start.sh Issue

### ISSUE THREAD

**Issue by yanaymi** [Pizzaface/Alexa-Chromecast-Skill-2.0#24]
I am using an Ubuntu virtual machine and I did it all until finally reaching the point where i executed: ./start.sh
My Chromecast name is 'Living Room' and This is what i got:
Traceback (most recent call last):
  File "./src/local/main.py", line 22, in <module>
    chromecast_skill = Skill(chromecast_name=os.getenv('CHROMECAST_NAME', 'Livin                             g Room'))
  File "/home/yanaymiz/alexaskill/alexa/src/local/ChromecastSkill.py", line 11,                              in _init_
    self.cast = next(cc for cc in chromecasts if cc.device.friendly_name == chro                             mecast_name)
StopIteration
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/pychromecast/socket_client.py", l                             ine 336, in run
  File "/usr/lib/python2.7/logging/__init__.py", line 1636, in debug
  File "/usr/lib/python2.7/logging/__init__.py", line 1541, in basicConfig
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

What should i do?﻿

**Comment by yanaymi** [comment]
Updating that i ran:
python -c 'import pychromecast; chromecasts = pychromecast.get_chromecasts(); print(chromecasts)'
And this is what i got:
[Chromecast('10.0.0.5', port=8009, device=DeviceStatus(friendly_name=u'Living Room', model_name=u'Chromecast', manufactu             rer=u'Google Inc.', api_version=(1, 0), uuid=UUID('0be43325-4c05-f4eb-1c28-745705462cbf'), cast_type='cast'))]

**Comment by jinxo13** [comment]
Can you try the latest version. This issue should be resolved.

**Comment by yanaymi** [comment]
Where cab i get the skill? The github link i found via google search doesnt
work

בתאריך יום ב׳, 13 ביולי 2020, 01:05, מאת Hamish McNeish ‏<
notifications@github.com>:

**Comment by jinxo13** [comment]
From this repository: https://github.com/Pizzaface/Alexa-Chromecast-Skill-2.0
I'm running this on Ubuntu.
